### ISSUE TITLE
Question on bin/setup step

### ISSUE THREAD

**Issue by Westie83** [Westie83/score-bored#2]
Since I don’t know how, I’m looking to add the basic terminal instructions that will explain how to navigate to the correct place in the repository in order to run bin/setup from there and install the application.

is there a step wehre the repository itself has been downloaded from github to my machine?

i can search the github faq for this basic info as well..if there is an explanation newbies should look at i would even consider providing that link

**Comment by gcentauri** [comment]
Can you show me how you cloned the repo yourself?

with the terminal i'd do something like:

```
# make sure we go to the home directory
cd
# create a projects/ directory
mkdir projects
cd projects
git clone https://github.com/westie83/score-bored
ls
cd score-bored
ls
ls bin
bin/setup
```

something like that :) the `ls` lines are just so you can see what is in the directory

**Comment by gcentauri** [comment]
i am sure there is a fantastic "Clone your First Repo!" article out there, but I am unfamiliar with The GitHub Way, if there is one.

I know there is a github app that you may be using, and I am not sure where it defaults to put its stuff!

There are many ways to open a terminal where you want, if you're used to a file browser, sometimes right clicking will allow you to open a terminal there. 

if you're using something like VSCode where you use its tools to clone your project, usually it has a way to open a terminal there as well.

i guess what i'm saying is, "it depends" but what i wrote above, will work if we just assume we're starting off in a terminal :)

**Comment by Westie83** [comment]
That’s what I was looking for, I think, because I did not clone the repo and I was not aware of that step. In my language it’s “download” - I don’t know how to “download and install the app” because this is not the app store lol

Thank you for the explanation! I too am sure that github has a way of teaching this, but I had not yet come across it. It’s possible I lack patience and (in spite of what I always say on my resume) attention to detail.

**Comment by gcentauri** [comment]
Cool! Once again I make assumptions about what a new GitHub user might already know!

FWIW I just came across this `git` tutorial this morning while browsing envs.net, a similar thingy to cicadas.surf https://help.envs.net/tutorials/learngit/docs/

**Comment by gcentauri** [comment]
![image](https://github.com/Westie83/score-bored/assets/760104/ba58a0fe-e47d-4bb3-99bf-095253e2e582)
 
The web interface has a few options.

If you have an SSH key setup (another thing to document or find docs for) you can use the SSH url.

I have never used GitHub CLI, but it probably does fun stuff.

**Comment by Westie83** [comment]
an update I got as far as bin/setup, meaning i DID successfully do the clone, my first ever. 
== Command ["bundle install"] failed == was the result of trying to run bin/setup but it's very probable that my debian system is missing many things. i'm happy with where this is going though, as i'm learning a lot.

**Comment by Westie83** [comment]
i think i'll close this now because the primary question was how to clone, and now i think i can return to the instructions and trying to see about asdf and the tools versions needed
